repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
  hooks:
    -   id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
-   repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.1
  hooks:
    -   id: add-trailing-comma
- repo: https://github.com/pycqa/isort
  rev: 5.5.2
  hooks:
    - id: isort
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
  - id: docformatter
      args: [--in-place]
