repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [types-requests==2.26.3, typing-extensions==3.10.0.2]
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place]
